---
abstract: 'Asynchronous Ext.Direct client in Perl'
author:
  - 'Alex Tokarev <tokarev@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  RPC::ExtDirect::Server: 1.01
  Test::More: 0.82
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPC-ExtDirect-Client-Async
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent::HTTP: 2.00
  RPC::ExtDirect::Client: 1.03
  perl: 5.008
resources:
  bugtracker: https://github.com/nohuhu/RPC-ExtDirect-Client-Async/issues
  repository: https://github.com/nohuhu/RPC-ExtDirect-Client-Async
version: 1.00
